# Generated by Django 2.1.2 on 2018-10-20 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomechecker', '0002_auto_20181020_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
