# Generated by Django 2.1.2 on 2018-10-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomechecker', '0003_auto_20181020_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypay',
            name='month_earning',
            field=models.CharField(max_length=50),
        ),
    ]
